### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by mjpost** [pmichel31415/mtnt#4]
I have a few questions about evaluation:

1. Did you use `-tok intl` for all directions (en-fr, fr-en, ja-en, en-ja), or just for en-ja?

2. The instructions specify to run:

       kytea -m /path/to/kytea/share/kytea/model.bin -notags out.detok > out.seg
       kytea -m /path/to/kytea/share/kytea/model.bin -notags ref.detok > ref.seg
       cat out.seg | sacrebleu --tokenize=intl ref.seg

      a. After installing KyTea, the model is actually under `/path/to/kytea/data/model.bin`. Can you confirm this is the same model you used above?

      b. The command above seems to introduce a lot of stray `\` characters, which will affect the BLEU score. Is this a problem?

       $ sacrebleu -t mtnt1.1/test -l en-ja --echo ref | mid 3
       メイン・ショー　1）中村スタイル（群衆を誇示するために）2）米国タイトル　3）ロー女子タイトル　4）SDタグ・タイトル　5）ブライアン/シェーン vs. KO/Sami 6）ICタイトル　7）バー vs. ブラウン 8）セナ-テイカー　9）SD女子タイトル　10）HHH/ステフ vs. アングル/ロンダ 11）ブロック-ローマン
       $ sacrebleu -t mtnt1.1/test -l en-ja --echo ref | mid 3 | ~/code/kytea/src/bin/kytea -model ~/code/kytea/data/model.bin -notags
       メイン ・ ショー 　 1 ） 中村 スタイル （ 群衆 を 誇示 する ため に ） 2 ） 米国 タイトル 　 3 ） ロー 女子 タイトル 　 4 ） SD タグ ・ タイトル 　 5 ） ブライアン \/ シェーン \  vs . \  KO \/ Sami \  6 ） IC タイトル 　 7  ） バー \  vs . \  ブラウン \  8 ） セナ - テイカー 　 9 ） SD 女子 タイトル 　 10 ） HHH \/ ステフ \  vs . \  アングル \/ ロンダ \  11 ） ブロック - ローマン

      ([mid](https://github.com/mjpost/bin/blob/master/mid) is a command that prints the Nth line of an input stream or file(s).

**Comment by pmichel31415** [comment]
Hi!

1. I used `--tokenize=intl` for all directions

2. Thanks for bringing that to my attention, seems like these instructions are a bit outdated, specifically

a. I *think* this is the same. to be more specific, I use the model in `$INSTALL_DIR/share/kytea/model.bin` where `$INSTALL_DIR` is the install dicrectory that you specify with `./configure --prefix $INSTALL_DIR`. In any case I checked the md5 hash and those 2 models are the same. TL;DR: **yes**

b. I actually double checked and the command I used is the one in https://github.com/pmichel31415/mtnt/blob/master/scripts/bleu_ja.sh , with `-out tok` instead of `-notags`:

```bash
sacrebleu -t mtnt1.1/test -l en-ja --echo ref | sed -n '3p' | kytea -model ~/kytea/share/kytea/model.bin -out tok
メイン ・ ショー 　 1 ） 中村 スタイル （ 群衆 を 誇示 する ため に ） 2 ） 米国 タイトル 　 3 ） ロー 女子 タイトル 　 4 ） SD タグ ・ タイトル 　 5 ） ブライアン / シェーン   vs .   KO / Sami   6 ） IC タイトル 　 7 ） バー   vs .   ブラウン   8 ） セナ - テイカー 　 9 ） SD 女子 タイトル 　 10 ） HHH / ステフ   vs .   アングル / ロンダ   11 ） ブロック - ローマン
```

I will update the readme, thanks for flagging

**Comment by mjpost** [comment]
Great, thanks. I didn't run `make install` so maybe that explains 2(a).

I assume you'll be using the same settings for the [robustness task](http://www.statmt.org/wmt19/robustness.html)?

**Comment by pmichel31415** [comment]
Yes we will
